### PR TITLE
coral-web: fix typo in os.ts

### PR DESCRIPTION
**Pull request by eltociear**
retuns -> returns

### CODE REVIEW

**Comment by lusmoura** [comment]
Thanks for spotting the typo and for contributing to fixing it!! 😄 
Would you mind rebasing your PR, we had an issue with our tests that should be fixed now!

**Comment by eltociear** [comment]
@lusmoura Which base should I change to?

**Comment by lusmoura** [comment]
> @lusmoura Which base should I change to?

The most recent main should work!

**Comment by tianjing-li** [comment]
Merging this

**Pull request merged**
