### PR TITLE
Changed Makefile for podman usage

### PR DESCRIPTION
**Pull request by fbanespo1**
Thank you for contributing to the Cohere Toolkit!

Description:
This PR replaces docker compose with podman compose in the Makefile to align with policies in organizations where Docker is no longer permitted. It updates the tooling to support podman, which provides a container management solution compatible with environments requiring alternative container engines.
Issue: No specific issue referenced.
Dependencies: Ensure podman and podman compose are installed in the environment before using the updated Makefile.
Add tests and docs: Documentation has been updated to reflect the usage of podman compose. Testing includes verification of make commands with podman environments.
Lint and test: Run make lint and make run-tests successfully to ensure changes pass all checks.
AI Description

This PR introduces a significant change to the project's build system by replacing Docker with Podman. This change is reflected across various commands and scripts, ensuring a consistent use of Podman throughout the project.

## Changes:
- In the `watch` command, the `docker compose` command has been replaced with `podman-compose`.
- The `up` command now uses `podman-compose` instead of `docker compose`.
- The `down` command has been updated to use `podman-compose`.
- The `run-integration-tests` command now utilizes `podman-compose` instead of `docker compose`.
- The `logs` command has been modified to use `podman-compose` for logging.
- The `exec-backend`, `exec-db`, and `exec-terrarium` commands now execute with `podman` instead of `docker`.
- The `migration`, `migrate`, and `downgrade` commands have been updated to use `podman-compose`.
- The `reset-db` command now combines `podman-compose down` and `podman volume rm cohere_toolkit_db`.
- The `test-db` command has been adjusted to use `podman-compose` for stopping, removing, and starting the test database.
- The `dev-sync` and `dev-sync-down` commands now employ `podman-compose` for managing the sync worker, publisher, and flower services.

### CODE REVIEW

**Comment by tianjing-li** [comment]
Wouldn't this change require all existing users to switch to Podman? I'm not sure switching out all our commands from docker -> podman is the right approach here for compatibility

**Comment by fbanespo1** [comment]
Hello, this is not for changing the "world" it's just another Makefile for
podman because companies with a lot of employee, like the one where I am
working cannot use docker anymore in the company laptop, but we are allowed
to use only podman.

**Comment by tianjing-li** [comment]
@fbanespo1 I understand your use-case, however you are trying to merge your changes into the main `Makefile`. If you'd like to merge your changes, I would suggest adding a compatible `Makefile.podman` instead

**Comment by fbanespo1** [comment]
> @fbanespo1 I understand your use case, however you are trying to merge your changes into the main `Makefile`. If you'd like to merge your changes, I would suggest adding a compatible `Makefile.podman` instead

Thank you. Committed and pushed the Makefile.podman

**Review by tianjing-li — APPROVED** [review]

**Comment by tianjing-li** [comment]
Approved! You'll have to sign the license agreement and your commits as well, you can check out the contributing.md doc for how to set those up

**Pull request closed without merging**
