### PR TITLE
Routers: add versioning

### PR DESCRIPTION
**Pull request by lusmoura**
Add v1 to all existing endpoints and fix FE routes

### CODE REVIEW

**Comment by tianjing-li** [comment]
What do you think about adding a `v1` folder inside `router` that will contain all the current routes?

**Comment by lusmoura** [comment]
> What do you think about adding a `v1` folder inside `router` that will contain all the current routes?

I thought about it, but I didn't want to overcomplicate the current structure. I'd suggest adding a new folder once we add a v2. What do you think? I can do it now if you have a strong opinion about adding the folder tho

**Comment by tianjing-li** [comment]
@lusmoura nah no big deal, we probably won't have a v2 for a while, I think this is good to go

**Review by tianjing-li — APPROVED** [review]
good to go

**Review by scott-cohere — APPROVED** [review]

**Pull request merged**
