### PR TITLE
Minro refactoring for consistancy sake

### PR DESCRIPTION
**Pull request by Phodaie**
".

2. The description should provide more details about the changes made in the pull request. It should also be concise and start with "

" and end with "

### CODE REVIEW

**Review by lusmoura — APPROVED** [review]
Nice catch! Thanks for contributing

**Comment by lusmoura** [comment]
Merging to avoid the need to update the branch again! 😅

**Comment by lusmoura** [comment]
I see one of the commits is not signed so you won't be able to merge the PR as is. To fix this, you can run the following command to sign all the commit history:

`exec git commit --amend --no-edit -S`

**Comment by Phodaie** [comment]
Good morning,I have signed my commit. Please let me know if there is anything else I need to do.BTW, I enjoyed browsing the toolkit source code and learned a lot from it.Have a wonderful day,Payman Sent from my iPhoneOn May 8, 2024, at 5:18 AM, Luísa Moura ***@***.***> wrote:﻿
I see one of the commits is not signed so you won't be able to merge the PR as is. To fix this, you can run the following command to sign all the commit history:
exec git commit --amend --no-edit -S

**Review by scott-cohere — APPROVED** [review]

**Comment by scott-cohere** [comment]
Hey @Phodaie! Thanks for checking out and contributing to Toolkit! Seems like your commits are still unverified. Check out https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits for more info about signing commits!

**Comment by scott-cohere** [comment]
@Phodaie looks good now. merging this in! thanks for your contribution :)

**Pull request merged**
